-- ================================================================
-- MIGRATION: Inserimento clienti Studio Mazzella
-- Esegui questo script su Supabase → SQL Editor
-- ================================================================

INSERT INTO clienti (tipo, ragione_sociale, nome, cognome, partita_iva, stato, note)
VALUES
('societa',        'Monica Pugliese SRL',                              NULL,           NULL,                NULL,           'attivo', NULL),
('societa',        'MERCURIO SRL',                                     NULL,           NULL,                '0384670631',   'attivo', 'Responsabile: GIANNI MARTORELLI'),
('persona_fisica', NULL,                                               'BERARDO',      'SCHIANO',           NULL,           'attivo', NULL),
('societa',        'MAZZELLA GABRIELA',                                NULL,           NULL,                '10485671217',  'attivo', NULL),
('societa',        'AN.DO. SRLS',                                      NULL,           NULL,                '10738061216',  'attivo', NULL),
('societa',        'B.F.M. S.A.S. DI ROCCO CONSIGLIA & C.',           NULL,           NULL,                '06633350639',  'attivo', NULL),
('persona_fisica', NULL,                                               'GABRIELLA',    'BOCCIA',            '10759361214',  'attivo', NULL),
('societa',        'C.E.M. S.R.L.',                                    NULL,           NULL,                '08410691219',  'attivo', NULL),
('persona_fisica', NULL,                                               'LUIGI',        'CARANNANTE',        '04789101211',  'attivo', NULL),
('persona_fisica', NULL,                                               'ANTONIO',      'MATTERA',           '06415821211',  'attivo', NULL),
('societa',        'Max Power service di ESPOSITO GIACOMO',            NULL,           NULL,                '05513511211',  'attivo', NULL),
('persona_fisica', NULL,                                               'GIUSEPPE',     'MAZZELLA',          '04813310630',  'attivo', NULL),
('societa',        'MI.CA.R.G. CATERING S.A.S.',                       NULL,           NULL,                '06508490635',  'attivo', NULL),
('societa',        'MIDO ELETTRONICA S.R.L.',                          NULL,           NULL,                '05545501214',  'attivo', NULL),
('persona_fisica', NULL,                                               'ENZO',         'MIRABELLA',         '08543931219',  'attivo', NULL),
('societa',        'MIRAOIL S.N.C.',                                   NULL,           NULL,                '07484430637',  'attivo', NULL),
('societa',        'MOBY DICK SAS DI TRAVAGLIO DARIO & C.',            NULL,           NULL,                '04604881211',  'attivo', NULL),
('societa',        'NAUTICA SCIROCCO DI ESPOSITO MICHELE',             NULL,           NULL,                '10250351219',  'attivo', NULL),
('societa',        'NON SOLO MOZZARELLA S.A.S.',                       NULL,           NULL,                '04828241218',  'attivo', NULL),
('societa',        'OFFICINA MECCANICA GENERALE S.R.L.S.',             NULL,           NULL,                '08891071212',  'attivo', NULL),
('persona_fisica', NULL,                                               'ANTONIO',      'PANARESE',          '05339160631',  'attivo', NULL),
('persona_fisica', NULL,                                               'GIADA',        'PANARESE',          '10385581219',  'attivo', NULL),
('persona_fisica', NULL,                                               'LUIGI',        'PUGLIESE',          '06910311213',  'attivo', NULL),
('societa',        'PUTEOLI SPURGO S.A.S.',                            NULL,           NULL,                '06969380630',  'attivo', 'Responsabile: GENNARO GAUDINO'),
('societa',        'RA. LU. S.A.S. DI LUCA LAMBERTI & C.',            NULL,           NULL,                '10149291212',  'attivo', NULL),
('societa',        'RDSP FOOD S.R.L.',                                 NULL,           NULL,                '07906621219',  'attivo', NULL),
('societa',        'RO.AS. S.A.S. DI DI PINTO ANTONIO & C.',          NULL,           NULL,                '06489951217',  'attivo', NULL),
('societa',        'S.C. IMPIANTI DI CAPUANO SALVATORE',              NULL,           NULL,                '05786671213',  'attivo', NULL),
('persona_fisica', NULL,                                               'MICHELE',      'SCHIANO MORIELLO',  '07259581218',  'attivo', NULL),
('societa',        'SCHIANO S.A.S.',                                   NULL,           NULL,                '05626390636',  'attivo', 'Responsabile: SCHIANO PROCOLO'),
('persona_fisica', NULL,                                               'GRETA',        'SCOTTO D''ANIELLO', '10715331210',  'attivo', NULL),
('persona_fisica', NULL,                                               'VINCENZO',     'SCOTTO D''ANTUONO', '07835440632',  'attivo', NULL),
('persona_fisica', NULL,                                               'MARIA TERESA', 'SCOTTO DI FREGA',   '10710651216',  'attivo', NULL),
('societa',        'VIVI ANT DI ORSELLI ALFREDO',                      NULL,           NULL,                '07840341213',  'attivo', 'Responsabile: ORSELLI ALFREDO'),
('persona_fisica', NULL,                                               'PASQUALE',     'COLANDREA',         '06836000635',  'attivo', NULL),
('persona_fisica', NULL,                                               'GABRIELLA',    'COLECCHIA',         '07196470632',  'attivo', NULL),
('societa',        'CURRIER S.A.S. Di Capuano Gennaro & C.',           NULL,           NULL,                '07505470638',  'attivo', NULL),
('persona_fisica', NULL,                                               'ROBERTO',      'DI TONTO',          '08735361217',  'attivo', NULL),
('societa',        'DO SO S.R.L.S.',                                   NULL,           NULL,                '10708011217',  'attivo', NULL),
('persona_fisica', NULL,                                               'MAURO',        'ESPOSITO',          '08604701212',  'attivo', NULL),
('persona_fisica', NULL,                                               'DAVIDE',       'FASCELLI',          '09165081218',  'attivo', NULL),
('societa',        'FEVOLA SAS DI SCOTTO D''ANTUONO',                  NULL,           NULL,                '04739530634',  'attivo', NULL),
('societa',        'FIVE BY ONE SNC DI LAMBERTI LUCA & C.',            NULL,           NULL,                '04818691216',  'attivo', 'Responsabile: ILLIANO GIUSEPPE'),
('societa',        'G.R. S.R.L.S.',                                    NULL,           NULL,                '08721181215',  'attivo', NULL),
('societa',        'GLEN.SAS DI ESPOSITO GIUSEPPE',                    NULL,           NULL,                '07030240639',  'attivo', NULL),
('societa',        'GIUMAR SERVICE',                                   NULL,           NULL,                '10628231218',  'attivo', NULL),
('persona_fisica', NULL,                                               'FEDERICA',     'GIUMELLO',          '08567581213',  'attivo', NULL),
('societa',        'HAPPY FOOD SRLS',                                  NULL,           NULL,                '08870431213',  'attivo', NULL),
('societa',        'HO.GI. SRL',                                       NULL,           NULL,                '07827180634',  'attivo', 'Responsabile: ILLIANO MARIA'),
('societa',        'LA TAVERNA DEI SAPORI DI FRATELLINI MARIELLA',     NULL,           NULL,                '04662241217',  'attivo', NULL),
('persona_fisica', NULL,                                               'PROCOLO',      'LAMBERTI',          '10290091213',  'attivo', NULL),
('societa',        'LAS VEGAS SNC',                                    NULL,           NULL,                '07283930639',  'attivo', NULL),
('persona_fisica', NULL,                                               'MARIKA',       'LOOZ',              '10703341213',  'attivo', NULL),
('persona_fisica', NULL,                                               'NICOLA',       'MANCINO',           '09411271217',  'attivo', NULL),
('societa',        'LA FOCACCERIA MONTESE',                            NULL,           NULL,                '10290091213',  'attivo', 'Responsabile: PROCOLO LAMBERTI');
